name: Build and deploy docs

on:
  push:
    branches:
      - develop

jobs:
  github-pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: helaili/jekyll-action@2.4.0
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          jekyll_src: docs
          target_branch: gh-pages
          gem_src: docs
